services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    hostname: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_server_memory_heap_initial__size=128M
      - NEO4J_server_memory_heap_max__size=128M
      - NEO4J_server_memory_pagecache_size=128M
    volumes:
      - ./infrastructure/neo4j/data:/data
      - ./infrastructure/neo4j/certificates:/ssl
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M

  web-apps:
    build:
      context: ./web-apps
      dockerfile: Dockerfile
    container_name: web-apps
    ports:
      - "${WEB_APPS_HOST}:3000"
    environment:
      - NODE_ENV=production
    restart: always
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "${BACKEND_SERVICE_HOST}:3000"
    environment:
      - NODE_ENV=production
    restart: always
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
