networks:
  app-network:
    driver: bridge

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    hostname: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      - NEO4J_server_memory_heap_initial__size=128M
      - NEO4J_server_memory_heap_max__size=128M
      - NEO4J_server_memory_pagecache_size=128M
    volumes:
      - ./infrastructure/neo4j/data:/data
      - ./infrastructure/neo4j/certificates:/ssl
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./infrastructure/redis/data:/data
    command: ["redis-server", "--requirepass", "$REDIS_PASSWORD"]
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"

  web-apps:
    build:
      context: .
      dockerfile: web-apps/Dockerfile
    container_name: web-apps
    ports:
      - "${WEB_APPS_PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - BACKEND_SERVICE_HOST=http://backend-service:3001
      - WEB_APPS_SOCKET_HOST=ws://backend-service:3001
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
  backend-service:
    build:
      context: ./backend-service
      dockerfile: Dockerfile
    container_name: backend-service
    ports:
      - "${BACKEND_SERVICE_PORT}:3001"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEO4J_URL=bolt://neo4j:7687
      - REDIS_HOST=redis
    restart: always
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: 2
          memory: 512M
