name: Backend Service CI

on:
  push:
    paths:
      - 'backend-services/**'

jobs:
  ci-backend-services:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js With Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run test
        run: pnpm run test

      - name: Build project
        run: pnpm run build
