name: CI

on:
  push:
    paths:
      - 'web-apps/**'
      - 'backend-services/**'
      - 'worker/**'

jobs:
  ci-web-apps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-apps
    if: github.event_name == 'push' && (contains(github.event.head_commit.modified.*, 'web-apps/') || contains(github.event.head_commit.added.*, 'web-apps/'))
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js With Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        working-directory: ./web-apps
        run: pnpm run lint

  ci-backend-services:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-service
    if: github.event_name == 'push' && contains(github.event.head_commit.added, 'backend-service/') || contains(github.event.head_commit.modified, 'backend-service/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js With Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run test
        run: pnpm run test

      - name: Build project
        run: pnpm run build

  ci-worker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./worker
    if: github.event_name == 'push' && contains(github.event.head_commit.added, 'worker/') || contains(github.event.head_commit.modified, 'worker/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js With Pnpm
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run test
        run: pnpm run test

      - name: Build project
        run: pnpm run build
