name: Web Apps CI

on:
  push:
    paths:
      - 'web-apps/**'

jobs:
  ci-web-apps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-apps
    strategy:
      matrix:
        node-version: [23]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
          cache-dependency-path: web-apps/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
      - name: Run lint
        run: pnpm run lint
      - name: Build project
        run: pnpm run build
